export const userConstants = {
  LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USER_LOGIN_FAILURE",

  LOGOUT: "USER_LOGOUT",

  LOGIN_SET_CODE: "USER_LOGIN_SET_CODE",
  LOGIN_SET_TOKEN: "USER_SET_TOKEN",
}
