version: "3.7"

services:
  api:
    image: ghcr.io/tech-with-tim/api:latest
    ports:
      - 5000:5000
    env_file: .env
    restart: unless-stopped
    environment:
      SECRET_KEY: key
      POSTGRES_URI: postgresql://api:api@db:5432/api

  cdn:
    image: techwithtim/cdn:latest
    env_file: .env
    restart: unless-stopped
    ports:
      - 8000:5000
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api
      DB_NAME: api
      DB_HOST: db
      DB_PORT: "5432"
      SECRET_KEY: key
      MAX_FILE_SIZE: "30"

  redis:
    image: redis:6.2.5-alpine

  websockets:
    image: techwithtim/websockets:latest
    restart: unless-stopped
    ports:
      - 5001:5000
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api
      DB_NAME: api
      DB_HOST: db
      DB_PORT: "5432"
      SECRET_KEY: key
      REDIS_HOST: redis
      REDIS_USERNAME: ""
      REDIS_PASS: ""
      REDIS_DB: "0"

  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ..:/workspace

  db:
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api
      POSTGRES_DB: api
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
