name: Build & Deploy

on:
  workflow_run:
    workflows: ["Lint & Test"]
    branches: ["prod"]
    types: ["completed"]
  workflow_dispatch:

jobs:
  build:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push'
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create SHA Container Tag
        id: sha_tag
        run: |
          tag=$(cut -c 1-7 <<< $GITHUB_SHA)
          echo "::set-output name=tag::$tag"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            techwithtim/frontend:${{ steps.sha_tag.outputs.tag }}
            techwithtim/frontend:latest
          builder: ${{ steps.buildx.outputs.name }}
          cache-to: type=local,dest=/tmp/.buildx-cache
          cache-from: type=local,src=/tmp/.buildx-cache

  deploy:
    name: Deploy on Kubernetes cluster
    runs-on: ubuntu-20.04
    needs: build

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          repository: Tech-With-Tim/k8s
          token: ${{ secrets.REPO_TOKEN }}

      - name: Create SHA Container Tag
        id: sha_tag
        run: |
          tag=$(cut -c 1-7 <<< $GITHUB_SHA)
          echo "::set-output name=tag::$tag"

      - name: Deploy to Kubernetes
        uses: fjogeleit/yaml-update-action@master
        with:
          repository: Tech-With-Tim/k8s
          token: ${{ secrets.REPO_TOKEN }}
          branch: "main"
          createPR: "false"
          updateFile: "true"
          message: "Redeploy Frontend: `${{ steps.sha_tag.outputs.tag }}`"
          valueFile: "frontend/deployment.yml"
          propertyPath: "spec.template.spec.containers.0.image"
          value: "techwithtim/frontend:${{ steps.sha_tag.outputs.tag }}"
