name: Lint & Test

on:
  push:
    branches:
      - '**'
      - '!prod'
  pull_request:

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Run Linting
        run: npm run lint

#       - name: Install Codecov
#         run: npm install -g codecov

#       - name: Run Tests & Report Coverage
#         run: npm run test:cov && codecov

      - name: Test building
        run: npm run build
