name: Lint & Test

on:
  push:
    paths:
      - "src/**"
      - "public/**"
      - ".eslintrc.json"
      - "prettierrc.json"
      - ".yarnrc.yml"
      - "next-env.d.ts"
      - "next.config.js"
      - "package.json"
      - "tsconfig.json"
      - "yarn.lock"
  pull_request:
    paths:
      - "src/**"
      - "public/**"
      - ".eslintrc.json"
      - "prettierrc.json"
      - ".yarnrc.yml"
      - "next-env.d.ts"
      - "next.config.js"
      - "package.json"
      - "tsconfig.json"
      - "yarn.lock"

jobs:
  packages:
    name: Install Dependencies
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ./node_modules
            ./.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-2

      - name: Install Packages
        run: yarn install
      
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    needs: packages
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Restore Cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ./node_modules
            ./.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-2
        
      - name: Run lint
        run: yarn run lint
  
  # TODO: tesitng job 
  
  build:
    name: Build
    runs-on: ubuntu-20.04
    needs: 
     - packages
     - lint
    env:
      NEXT_TELEMETRY_DISABLED: 1
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Restore Cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ./node_modules
            ./.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-2
        
      - name: Run build
        run: yarn run build
